// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLVs9r_22ZvnjrfAd_upTMkhjaQZUR7g',
    appId: '1:319365283963:web:0f2ecff5bbbbf790d222de',
    messagingSenderId: '319365283963',
    projectId: 'device-streaming-a1af3b70',
    authDomain: 'device-streaming-a1af3b70.firebaseapp.com',
    storageBucket: 'device-streaming-a1af3b70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBILTCMDVFFqF_-Joa32HUKduMpkhezuhc',
    appId: '1:319365283963:android:45be7ff1c040fdded222de',
    messagingSenderId: '319365283963',
    projectId: 'device-streaming-a1af3b70',
    storageBucket: 'device-streaming-a1af3b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXPJDLIc9IbfOZcGOcFHvkhraVd-_jYl4',
    appId: '1:319365283963:ios:d6573e6645f69c55d222de',
    messagingSenderId: '319365283963',
    projectId: 'device-streaming-a1af3b70',
    storageBucket: 'device-streaming-a1af3b70.firebasestorage.app',
    iosBundleId: 'com.example.family',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXPJDLIc9IbfOZcGOcFHvkhraVd-_jYl4',
    appId: '1:319365283963:ios:d6573e6645f69c55d222de',
    messagingSenderId: '319365283963',
    projectId: 'device-streaming-a1af3b70',
    storageBucket: 'device-streaming-a1af3b70.firebasestorage.app',
    iosBundleId: 'com.example.family',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHLVs9r_22ZvnjrfAd_upTMkhjaQZUR7g',
    appId: '1:319365283963:web:13f8094a952196f1d222de',
    messagingSenderId: '319365283963',
    projectId: 'device-streaming-a1af3b70',
    authDomain: 'device-streaming-a1af3b70.firebaseapp.com',
    storageBucket: 'device-streaming-a1af3b70.firebasestorage.app',
  );

}